import type { Metadata } from "next";
import { Baskervville } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

const baskervville = Baskervville({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={baskervville.className}>{children}</body>
      </html>
    </ClerkProvider>
  );
}
